
[block_chain]
chain_id = 5
ws_url = "wss://goerli.gateway.tenderly.co"
uniswap_factory_v3_address = "0x92425fce1d58b614CbBbA41F39F9850abD10EB71"
uniswap_router_v3_address = "0xe592427a0aece92de3edee1f18e0157c05861564"
nonfungible_position_manager_address = "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"
usdt_address = "0x98890904E58f01ad8717dfC9D7DA43a1E01EDAD1"
usdc_address = "0xd8D096F8F6bCaDc23b05Bf9EbE6c0356d635eFBe"
weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
gas_price = 1000

[database]
username = "root"
password = "rootroot"
host = "localhost"
database_name = "uniswap_v3"
max_connections = 100
min_connections = 5

[server]
port = 8080
timeout = 180

[log]
log_dir = "./logs"
