
[block_chain]
chain_id = 1
ws_url = "wss://mainnet.gateway.tenderly.co"
uniswap_factory_v3_address = "0x1f98431c8ad98523631ae4a59f267346ea31f984"
uniswap_router_v3_address = "0xe592427a0aece92de3edee1f18e0157c05861564"
usdt_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
usdc_address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
gas_price = 1000
 
[database]
username = "root"
password = "rootroot"
host = "localhost"
database_name = "uniswap_v3"
max_connections = 100
min_connections = 5

[server]
port = 8080
timeout = 180

[log]
log_dir = "./logs"
